project:
  type: book
  output-dir: _site

execute: 
  enabled: true

lang: de
book:
  title: "Einf√ºhrung in die lineare Optimierung"
  author: "Boyko Amarov"
  date: last-modified
  chapters:
    - index.qmd
    - 01-Introduction.ipynb
    - 02-Blending.ipynb
    - 03-Sensitivity-Analysis-Class.ipynb
    # - 02-Graphical-Method/02-Blending.ipynb
    # - 02-Graphical-Method/03-Sensitivity-Analysis.ipynb

    # - part: "Anwendungen"
    #   chapters:
    #     - IP-Urban-Planning.ipynb
    #     - LP-Diet.ipynb
    #     - Job-Assignment.ipynb
    #     - Milonga-Ex.ipynb
    #     - Prediction-Ex.ipynb
    #     - Prediction.ipynb
    #     - Lineare-Algebra.ipynb
    #     - Cocktails-Excel-Python.ipynb
    #     - Cocktails-Duality.ipynb
    #     - Cocktails-Algebra.ipynb
    #     - Max-Flow.ipynb
    #     - Production-Distribution.ipynb
    #     - cell_tower.ipynb
    #     # - Lineare-Algebra.ipynb
    #     # - Lineare-Algebra-Ex.ipynb
    # - Links.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    code-fold: true
    code-summary: "Anzeigen"
