project:
  type: book
  output-dir: _site

execute: 
  enabled: true

lang: de
book:
  title: "Einführung in die lineare Optimierung"
  author: "Boyko Amarov"
  date: last-modified
  chapters:
    - index.qmd
    # - Hausarbeiten.qmd
    - part: "Einführung in Python"
      chapters:
        - 01-Python/01-Basics.ipynb
        - 01-Python/02-Numpy.ipynb
        - 01-Python/03-Pandas.ipynb     
    - part: "Die graphische Methode"
      chapters:
        # - 03-Graphical-Method/00-Burritos.ipynb
        - 02-Graphical-Method/01-Berlin-Airlift.ipynb
        # - 02-Graphical-Method/02-Blending.ipynb
        # - 02-Graphical-Method/03-Sensitivity-Analysis.ipynb

    # - part: "Anwendungen"
    #   chapters:
    #     - IP-Urban-Planning.ipynb
    #     - LP-Diet.ipynb
    #     - Job-Assignment.ipynb
    #     - Milonga-Ex.ipynb
    #     - Prediction-Ex.ipynb
    #     - Prediction.ipynb
    #     - Lineare-Algebra.ipynb
    #     - Cocktails-Excel-Python.ipynb
    #     - Cocktails-Duality.ipynb
    #     - Cocktails-Algebra.ipynb
    #     - Max-Flow.ipynb
    #     - Production-Distribution.ipynb
    #     - cell_tower.ipynb
    #     # - Lineare-Algebra.ipynb
    #     # - Lineare-Algebra-Ex.ipynb
    # - Links.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    code-fold: false
    code-summary: "Anzeigen"
